# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: false
warnings_are_errors: false

env:
  global:
    - TENSORFLOW_TEST_EXAMPLES="1"

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - name: "TensorFlow (Stable)"
      env: TENSORFLOW_VERSION="default"
    - name: "TensorFlow Eager (Stable)"
      env:
        - TENSORFLOW_VERSION="default"
        - TENSORFLOW_EAGER="TRUE"
    - name: "Tensorflow (2.0.0-b0)"
      env:
        - TENSORFLOW_VERSION="2.0.0b0"
        - TENSORFLOW_TEST_EXAMPLES=""
    - name: "Tensorflow (1.14.0-rc1)"
      env:
        - TENSORFLOW_VERSION="1.14.0rc1"
        - TENSORFLOW_TEST_EXAMPLES=""
    - name: "TensorFlow (Nightly)"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "TensorFlow Eager (Nightly)"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"
  allow_failures:
    - name: "TensorFlow (Nightly)"
      env:
        - TENSORFLOW_VERSION="nightly"
    - name: "TensorFlow Eager (Nightly)"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_EAGER="TRUE"

before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'tensorflow::install_tensorflow(version = Sys.getenv("TENSORFLOW_VERSION"))'
  - R -e 'tensorflow::tf_config()'
